### ISSUE TITLE
Bitcoin icon issue

### ISSUE THREAD

**Issue by levimoto** [Richard9394/MingCute#1]
Related icons:
- currency_bitcoin_line
- currency_bitcoin_fill
- exchange_bitcoin_line
- exchange_bitcoin_fill

There are two vertical lines in Bitcoin.

Reference Unicode:
![image](https://user-images.githubusercontent.com/94159664/153822322-168430b3-ca4c-4e69-ad3a-ef145e16f0e7.png)

**Comment by Richard9394** [comment]
Thanks for your suggestion, we will fix it in the next version.

**Comment by Richard9394** [comment]
I'm glad to tell you that you can get the fixed bitcoin icon in version 2.1.&nbsp;
MingCute icon website：https://www.mingcute.com/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月14日(星期一) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Richard9394/MingCute] Bitcoin icon issue (Issue #1)





 
Related icons:
  
currency_bitcoin_line
 
currency_bitcoin_fill
 
exchange_bitcoin_line
 
exchange_bitcoin_fill
  
There are two vertical lines in Bitcoin.
 
Reference Unicode:
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
