### ISSUE TITLE
New Logo Icon Suggest

### ISSUE THREAD

**Issue by ElliottZhao** [Richard9394/MingCute#11]
Add logo of dingtalk.
[DingTalk Branding Authorization 2019.01](https://files.alicdn.com/tpsservice/118865795f9bbc47d63d5c70a40588e5.pdf?spm=ding_open_doc.document.0.0.c3bc4a9776iiJC&file=118865795f9bbc47d63d5c70a40588e5.pdf)

If you are able to read chinese, feel free to get resource from [this page](https://open.dingtalk.com/document/design-specification/download-resources)

Thanks

**Comment by Richard9394** [comment]
You can find it under the logo category in version 2.83.
