### ISSUE TITLE
The version of this repository is behind the website

### ISSUE THREAD

**Issue by DIYgod** [Richard9394/MingCute#13]
Thank you for providing such a wonderful icon library. I am currently utilizing the `@iconify-json/mingcute` package in my project. However, I have noticed that this repository is outdated and missing several icons compared to the official website, including `arow_to_up_line`. Therefore, I kindly request an update of the repository.

**Comment by Richard9394** [comment]
谢谢你的喜欢，MingCute图标库更新到了与官网一致的[v2.84](https://github.com/Richard9394/MingCute/releases/tag/v2.84)，如果方便请帮忙给项目星标⭐以推荐给更多人使用

**Comment by DIYgod** [comment]
⭐ 非常感谢！我再去推动下 `@iconify-json/mingcute` 的更新

希望可爱的 MingCute 越来越好，被更多人使用
