### ISSUE TITLE
能否设计一些有关人体部位的图标？

### ISSUE THREAD

**Issue by maxinhuang** [Richard9394/MingCute#2]
如今关于元宇宙的项目需要对人物进行捏脸，希望能够设计一些关于人体部位的图标，如脸型、眉毛、耳朵、眼睛、胡子、鼻子、嘴巴、身材、头发等

**Comment by Richard9394** [comment]
谢谢你的关注，已列入计划，将在后续的版本更新

**Comment by Richard9394** [comment]
人体部位图标绘制了10组，上线v2.2中，请到[MingCute官网](https://www.mingcute.com/)part分类中查看

**Comment by Richard9394** [comment]
``
