### ISSUE TITLE
unnecessary vectors

### ISSUE THREAD

**Issue by dinael** [Richard9394/MingCute#25]
I am a fan and user of your work, I think you make very original and beautiful icons.

But you have a problem, I think that in the template, you have some unnecessary vectors that cause a lot of problems, I am forced to review each of the icons and delete them.

I attach an image.
![image](https://github.com/Richard9394/MingCute/assets/3618283/08915f01-cbe8-422d-9aeb-ca1f71cdc006)

**Comment by Richard9394** [comment]
Thank you for your like. 
This part contains Mingcute label frames, which are used to keep the icons in a uniform 24 pixel size. 
They are transparent and have no fill color.
