### ISSUE TITLE
Need: Praying hands / Namaste icon

### ISSUE THREAD

**Issue by scottannan** [Richard9394/MingCute#27]

**Comment by Richard9394** [comment]
You can search "pray" in new version [v2.88](https://www.mingcute.com/)

**Comment by Richard9394** [comment]
> You're awesome, I really appreciate it. Thanks so much 🙏

You're welcome.
If it is convenient, please help [star](https://github.com/Richard9394/MingCute)⭐ the project to recommend it to more people.
