### ISSUE TITLE
大师，能否设计一些关于服装的图标？

### ISSUE THREAD

**Issue by maxinhuang** [Richard9394/MingCute#3]
1.套装、上衣、裤子、鞋子、袜子、头饰、眼镜、配饰

**Comment by maxinhuang** [comment]
2.缺少了很常用的“…”图标，自己设计的省略号图标总是感觉无法跟mingcute的风格匹配，希望能够补充

**Comment by maxinhuang** [comment]
3.希望增加“表情”图标，用于打开表情包

**Comment by Richard9394** [comment]
已记录，后续版本中逐步绘制更新

**Comment by Richard9394** [comment]
> 3.希望增加“表情”图标，用于打开表情包

表情图标绘制了2组，上线v2.3中，请到[MingCute官网](https://www.mingcute.com/)editor分类中查看

**Comment by Richard9394** [comment]
> 2.缺少了很常用的“…”图标，自己设计的省略号图标总是感觉无法跟mingcute的风格匹配，希望能够补充
更多图标绘制4组，上线v2.3中，请到[MingCute官网](https://www.mingcute.com/)system分类中查看

**Comment by Richard9394** [comment]
> 1.套装、上衣、裤子、鞋子、袜子、头饰、眼镜、配饰
You can find them in the part category of [MingCute](https://www.mingcute.com/) website
