### ISSUE TITLE
能否添加line app的图标

### ISSUE THREAD

**Issue by zhangsan996** [Richard9394/MingCute#4]
能否添加line app的图标
![image](https://user-images.githubusercontent.com/39147890/179713031-c592d8b6-1b6b-4afc-b672-060dcc20b465.png)

**Comment by Richard9394** [comment]
OK

**Comment by Richard9394** [comment]
The line app icon has been uploaded to the [MingCute](https://www.mingcute.com/) website. You can find it under the logo category in version 2.5. Please star the MingCute project.
