### ISSUE TITLE
Search function is case-sensitive 

### ISSUE THREAD

**Issue by Fintasys** [Richard9394/MingCute#40]
I was browsing through the icons but realized that they won't show up when I was searching for them. It turned out that auto correction wrote a lot of words with capital first letter and the search function is case-sensitive which makes it almost useless on mobile.

Hope you can fix that 😀
Beside that, thanks for the great collection of icons 🙏

**Comment by Richard9394** [comment]
Thank you for your feedback, we have fixed the issue with capitalization of letters in the search function.
