### ISSUE TITLE
图标新增建议

### ISSUE THREAD

**Issue by maxinhuang** [Richard9394/MingCute#5]
1.折叠列表全部展开
2.折叠列表全部折叠
3.“+”加号
4.四个圆点的网格
![微信截图_20220919002325](https://user-images.githubusercontent.com/100193096/190917662-b06f2aea-93c8-461b-a66a-46de4274d1b0.png)
![微信截图_20220919002345](https://user-images.githubusercontent.com/100193096/190917664-f4214a39-1170-4c20-a604-5d00f01b84e1.png)

**Comment by maxinhuang** [comment]
赞（thumb_down）、踩thumb_up、查找（search）的填充状态的辨识度比较低
查找图标建议在放大镜中间加一个实心圆

**Comment by Richard9394** [comment]
> 1.折叠列表全部展开 2.折叠列表全部折叠 3.“+”加号 4.四个圆点的网格 ![微信截图_20220919002325](https://user-images.githubusercontent.com/100193096/190917662-b06f2aea-93c8-461b-a66a-46de4274d1b0.png) ![微信截图_20220919002345](https://user-images.githubusercontent.com/100193096/190917664-f4214a39-1170-4c20-a604-5d00f01b84e1.png)
You can find them on the [MingCute](https://www.mingcute.com/) website version 2.7. 
1.list_collapse
2.list_expansion
3.add
4.classify

**Comment by Richard9394** [comment]
> 赞（thumb_down）、踩thumb_up、查找（search）的填充状态的辨识度比较低 查找图标建议在放大镜中间加一个实心圆

Get the new icons on the [MingCute](https://www.mingcute.com/) website.
1.thumb_up_2
2.thumb_down_2
3.search_3

**Comment by Richard9394** [comment]
Please star the MingCute project.
